# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkedindata',
            fields=[
                ('entryid', models.AutoField(db_column='entryId', primary_key=True, serialize=False, unique=True)),
                ('isvalid', models.IntegerField(blank=True, db_column='isValid', null=True)),
            ],
            options={
                'db_table': 'checkedindata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Extract',
            fields=[
                ('extractid', models.AutoField(db_column='extractId', primary_key=True, serialize=False, unique=True)),
                ('number', models.IntegerField(unique=True)),
                ('formingdate', models.DateField(blank=True, db_column='formingDate', null=True)),
                ('applicantinfo', models.CharField(blank=True, db_column='ApplicantInfo', max_length=255, null=True)),
                ('extractscol', models.CharField(blank=True, db_column='Extractscol', max_length=45, null=True)),
                ('personwhomadeextract', models.CharField(blank=True, db_column='PersonWhoMadeExtract', max_length=255, null=True)),
                ('personwhosignsextract', models.CharField(blank=True, db_column='PersonWhoSignsExtract', max_length=255, null=True)),
                ('personswhosignsextractpost', models.CharField(blank=True, db_column='PersonsWhoSignsExtractPost', max_length=255, null=True)),
            ],
            options={
                'db_table': 'extract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inpassport',
            fields=[
                ('passportid', models.AutoField(db_column='passportId', primary_key=True, serialize=False)),
                ('series', models.CharField(max_length=2)),
                ('number', models.IntegerField()),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=45, null=True)),
                ('secondname', models.CharField(blank=True, db_column='secondName', max_length=45, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=45, null=True)),
                ('birthdate', models.DateField(blank=True, db_column='birthDate', null=True)),
                ('birthplace', models.CharField(blank=True, db_column='birthPlace', max_length=45, null=True)),
                ('givendate', models.DateField(blank=True, db_column='givenDate', null=True)),
                ('givenby', models.CharField(blank=True, db_column='givenBy', max_length=45, null=True)),
            ],
            options={
                'db_table': 'inpassport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Negativereference',
            fields=[
                ('referenceid', models.AutoField(db_column='referenceId', primary_key=True, serialize=False, unique=True)),
                ('personwhomadereference', models.CharField(blank=True, db_column='PersonWhoMadeReference', max_length=255, null=True)),
                ('personwhosignsreference', models.CharField(blank=True, db_column='PersonWhoSignsReference', max_length=255, null=True)),
                ('personswhosignsreferencepost', models.CharField(blank=True, db_column='PersonsWhoSignsReferencePost', max_length=255, null=True)),
                ('negativereferencecol', models.CharField(blank=True, db_column='NegativeReferencecol', max_length=45, null=True)),
            ],
            options={
                'db_table': 'negativereference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('personid', models.AutoField(db_column='personId', primary_key=True, serialize=False, unique=True)),
                ('workplace', models.CharField(db_column='workPlace', max_length=255)),
                ('workpost', models.CharField(db_column='workPost', max_length=255)),
                ('checkresult', models.CharField(db_column='checkResult', max_length=255)),
                ('startingterm', models.DateField(db_column='StartingTerm')),
                ('taxcode', models.IntegerField(blank=True, db_column='TaxCode', null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Positivereference',
            fields=[
                ('idreference', models.AutoField(db_column='idReference', primary_key=True, serialize=False)),
                ('personwhomadereference', models.CharField(blank=True, db_column='PersonWhoMadeReference', max_length=255, null=True)),
                ('personwhosignsreference', models.CharField(blank=True, db_column='PersonWhoSignsReference', max_length=255, null=True)),
                ('personswhosignsreferencepost', models.CharField(blank=True, db_column='PersonsWhoSignsReferencePost', max_length=255, null=True)),
            ],
            options={
                'db_table': 'positivereference',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registeredpassport',
            fields=[
                ('passportid', models.AutoField(db_column='passportId', primary_key=True, serialize=False)),
                ('series', models.CharField(max_length=2)),
                ('number', models.IntegerField(unique=True)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=45, null=True)),
                ('secondname', models.CharField(blank=True, db_column='secondName', max_length=45, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=45, null=True)),
                ('birthdate', models.DateField(blank=True, db_column='birthDate', null=True)),
                ('birthplace', models.CharField(blank=True, db_column='birthPlace', max_length=45, null=True)),
                ('givendate', models.DateField(blank=True, db_column='givenDate', null=True)),
                ('givenby', models.CharField(blank=True, db_column='givenBy', max_length=45, null=True)),
            ],
            options={
                'db_table': 'registeredpassport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestid', models.AutoField(db_column='requestId', primary_key=True, serialize=False)),
                ('answertype', models.IntegerField(blank=True, db_column='answerType', null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=255, null=True)),
                ('secondname', models.CharField(blank=True, db_column='secondName', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=255, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('obtainway', models.IntegerField(blank=True, db_column='obtainWay', null=True)),
                ('applicantinfo', models.CharField(blank=True, db_column='ApplicantInfo', max_length=255, null=True)),
                ('servicenotes', models.TextField(blank=True, db_column='serviceNotes', null=True)),
                ('taxcode', models.IntegerField(blank=True, db_column='TaxCode', null=True)),
            ],
            options={
                'db_table': 'request',
                'managed': False,
            },
        ),
    ]
